<style type="text/css">
.thumbnail{
position: relative;
	  z-index: 0;
}
.thumbnail:hover{
	background-color: transparent;
	z-index: 50;
}
.thumbnail span{
position: absolute;
padding: 1px;
left: -1000px;
visibility: hidden;
color: black;
       text-decoration: none;
}
.thumbnail span img{
	border-width: 0;
padding: 2px;
}
.thumbnail:hover span{
visibility: visible;
top: 17px;
left: 50px;
}
</style>
